version: '3.4'
services:
  bundlifier:
    restart: on-failure
    build: .
    volumes:
      - ./:/bundlifier
    command: 'sh -c "chmod +x docker-compose-entrypoint.sh && ./docker-compose-entrypoint.sh"'
    #command: 'ls -la'
